---
title: "Departure time"
author: "XinyiLi73"
date: "2018/12/6"
output: html_document
---
```{r}
library(dslabs)
library(tidyverse)
library(dplyr)
library(shiny)
library(readr)

```

Generate departure hour, overall delay percentage, overall average delay hours, and delay percentage and average delay hours for each carrier (dat2 for percentage, dat3 for delay hour-only delayed flight included):
```{r}
dat1 <- dat %>% mutate(DEP_HOUR=as.numeric(substr(CRS_DEP_TIME,1,2))) ## departure hour extraction wrong

dat2<- dat1 %>%  filter(!is.na(DEP_DEL15)) %>%
  group_by(DEP_HOUR, DAY_OF_WEEK) %>%
  mutate(PERCENTAGE_OVERALL=mean(DEP_DEL15))
dat3<- dat1 %>% filter(!is.na(DEP_DELAY_NEW) & DEP_DEL15==1) %>%
  group_by(DEP_HOUR) %>%
  mutate(AVERAGE_OVERALL=mean(DEP_DELAY_NEW))

dat4 <- dat2 %>%  filter(!is.na(DEP_DEL15)) %>%
  group_by(OP_UNIQUE_CARRIER, DAY_OF_WEEK, DEP_HOUR) %>%
  mutate(PERCENTAGE=mean(DEP_DEL15))
dat5 <- dat3 %>% filter(!is.na(DEP_DELAY_NEW) & DEP_DEL15==1) %>%
  group_by(OP_UNIQUE_CARRIER,DEP_HOUR) %>%
  mutate(AVERAGE=mean(DEP_DELAY_NEW))
dat5
```

Heatmap for overall delay percentage:
```{r}
library(RColorBrewer)
dat2 %>% ggplot(aes(DEP_HOUR, DAY_OF_WEEK,  fill = PERCENTAGE_OVERALL)) +
  geom_tile(color = "white") +
  scale_fill_gradientn(colors = brewer.pal(9, "Reds"),limits=c(0,1)) +
  scale_y_continuous(breaks=seq(1,7))+
  theme_minimal() +  
  theme(panel.grid = element_blank()) +
  labs(title="Overall delay percentage in each hour and each day of week",y="Day of week",x="Departure hour")
```

Bar plot for overall average delay hours:
```{r}
dat3 %>% select(DEP_HOUR,AVERAGE_OVERALL) %>%
  unique() %>%
  ggplot(aes(DEP_HOUR,AVERAGE_OVERALL))+
  geom_bar(stat="identity", fill="#720017")+
  labs(title="Overall delay time in each hour and each day of week",y="Average delay time (minutes)",x="Departure hour")
```


```{r}
runApp("app.R")
```


